import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider } from '@clerk/nextjs'
import ThemeProviderZustand from '@/components/ThemeProviderZustand';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ThemeProviderZustand>
            {children}
          </ThemeProviderZustand>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
